### ISSUE TITLE
Read consistency

### ISSUE THREAD

**Issue by SimbaWei** [icsa-caps/ccKVS#3]
Hello katsarakis!
 I am reading your excellent paper work and codes in EuroSys.  Your work guarantee the global write serialization by broadcasting invalidation and updates. However, I wonder how your work implements the read consistency for gets? also using a Lamport clok for get operation?  If not, my understanding was that the latter get operation sometimes could not see the value from former set operation. I don't know whether this violate SC/Lin?
Looking forward your response!

Thanks in advance!

**Comment by akatsarakis** [comment]
Hello,

Thank you for your kind words.
Let me try to address your question.

ccKVS uses two protocols each one leveraging per-key Lamport clocks to offer either per-key Sequential Consistency or (per-key) Linearizability.
Most of the work for both protocols happens on writes. In fact, reads for per-key Sequential Consistency,  always immediately return the local value without any consistency violation*. For linearizability, the reads are the same except unless they encounter the key in the Invalid state, in which case they simply wait for the validation message before they return the value.
I would recommend taking a look on [Hermes](https://hermes-protocol.com/)' (fast path) more detailed protocol that is essentially the ccKVS Linearizable protocol that also offers fault-tolerance. 

* Note that while per-key Linearizability is equivalent to Linearizability (because linearizability is a local property) per-key sequential consistency is not the same as sequential consistency across keys.
